name: command_runner
description: A starting point for Dart libraries or applications.
version: 1.0.0
resolution: workspace

environment:
  sdk: ^3.8.1

dependencies:
  # тут могут быть зависимости, если есть

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
